name: GitHub Linux Release

on:
  workflow_run:
    workflows: [DualSense,DualShock4]
    branches: [nightly-pr]
    types:
      - completed

jobs:
  releases:
    runs-on: ubuntu-latest
    steps:
    - name: Execute build
      run: echo "success"

    - name: Download artifact
      uses: dawidd6/action-download-artifact@v2
      with:
        # Optional, GitHub token, a Personal Access Token with `public_repo` scope if needed
        # Required, if artifact is from a different repo
        #github_token: ${{secrets.GITHUB_TOKEN}}
        # Required, workflow file name or ID
        workflow: build.yml
        # Optional, the status or conclusion of a completed workflow to search for
        # Can be one of a workflow conclusion:
        #   "failure", "success", "neutral", "cancelled", "skipped", "timed_out", "action_required"
        # Or a workflow status:
        #   "completed", "in_progress", "queued"
        workflow_conclusion: success
        # Optional, no need to specify if PR is
        commit: ${{github.event.pull_request.head.sha}}
        # Optional, defaults to current repo
        repo: ${{github.repository}}

    - name: Display structure of downloaded files
      run: ls -R
