name: GitHub Linux Release

on:
  workflow_run:
    workflows: [DualSense]
    branches: [nightly-pr]
    types:
      - completed

jobs:
  releases:
    runs-on: ubuntu-latest
    steps:
    - name: Execute build
      run: echo "success"
